import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

import connectMongo from '../utils/connectMongo'
import Test from '../models/testModel'
// import Article_model from '../Models/articleModel'


import { useEffect, useState } from 'react'


export default function Home({articles}) {



const [articleList, setArticleList] = useState([])

useEffect(() => {
  setArticleList(articles)
}, [])


  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <h1>LE BLOG</h1>
        <p>Ceci est un blog</p>

    {articleList.map((item, index) => (
      <div key={index} >
        <h1> {item.name} </h1>
        <Link href={`${item._id}`} >Page</Link>
      </div>
    ))}
     
      </div>

    </div>
  )
}


export const getServerSideProps = async () => {
  try {
   
    await connectMongo();
  
    console.log("mongo connected");
    const articles = await Test.find()
    console.log('data fetched');

    return {
      props : {
        articles : JSON.parse(JSON.stringify(articles))
      }
    }
    
} catch (error) {
    console.log(error);
  
}
}